name: CI

on: [push, pull_request]

jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
          sudo apt-get -y install uuid-dev libcurl4-openssl-dev
          make -j2
    - name: upload-keydb-server
      uses: actions/upload-artifact@v1
      with:
        name: keydb-server
        path: src/keydb-server
    - name: test
      run: |
        sudo apt-get -y install tcl8.5
        ./runtest --clients 2 --verbose
    - name: cluster-test
      run: |
        ./runtest-cluster
    -name: build-deb-pkg
      run: |
        working-directory: ./pkg/deb/
        sudo ./deb-builder.sh
    - name: upload-deb-keydb-tools
      uses: actions/upload-artifact@v1
      with:
        name: keydb-tools_0.0.0-1chl1~bionic1_amd64.deb
        path: pkg/deb/deb_files_generated/keydb-tools_0.0.0-1chl1~bionic1_amd64.deb   

  test-ubuntu-arm:
    runs-on: [self-hosted, linux, arm]
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
          sudo apt-get -y install uuid-dev libcurl4-openssl-dev
          make -j4
    - name: test
      run: |
        sudo apt-get -y install tcl8.5
        ./runtest --clients 2 --verbose
    - name: cluster-test
      run: |
        ./runtest-cluster

  build-ubuntu-old:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: make -j2
      run: | 
        sudo apt-get -y install uuid-dev libcurl4-openssl-dev
        make

  build-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make -j2
